name: Supabase Tests

on:
  pull_request:
    paths:
      - "supabase/**"
      - ".github/workflows/supabase-test.yml"

  push:
    branches:
      - develop
    paths:
      - "supabase/**"
      - ".github/workflows/supabase-test.yml"

jobs:
  test:
    name: Test Supabase migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@ab058987d8d6c725971f6cf9d0b5c98467e30bd1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Reset database
        run: supabase db reset

      - name: Stop Supabase
        if: always()
        run: supabase stop
